//Lista 25 Exercícios - Ex 13

#include <stdio.h>

int main()
{
    int N, T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10;

    printf("Tabuada\n");
    printf("Digite um número: ");
    scanf("%d",&N);
    printf("\n");
    printf("Tabuada de Soma\n");
    printf("===============\n");
    T0 = N+0;
    T1 = N+1;
    T2 = N+2;
    T3 = N+3;
    T4 = N+4;
    T5 = N+5;
    T6 = N+6;
    T7 = N+7;
    T8 = N+8;
    T9 = N+9;
    T10 = N+10;
    printf("%d",N);
    printf(" + 0 = ""%d\n",T0);
    printf("%d",N);
    printf(" + 1 = ""%d\n",T1);
    printf("%d",N);
    printf(" + 2 = ""%d\n",T2);
    printf("%d",N);
    printf(" + 3 = ""%d\n",T3);
    printf("%d",N);
    printf(" + 4 = ""%d\n",T4);
    printf("%d",N);
    printf(" + 5 = ""%d\n",T5);
    printf("%d",N);
    printf(" + 6 = ""%d\n",T6);
    printf("%d",N);
    printf(" + 7 = ""%d\n",T7);
    printf("%d",N);
    printf(" + 8 = ""%d\n",T8);
    printf("%d",N);
    printf(" + 9 = ""%d\n",T9);
    printf("%d",N);
    printf(" + 10 = ""%d\n",T10);
    printf("\n");
    printf("Tabuada de Subtração\n");
    printf("====================\n");
    T0 = N-0;
    T1 = N-1;
    T2 = N-2;
    T3 = N-3;
    T4 = N-4;
    T5 = N-5;
    T6 = N-6;
    T7 = N-7;
    T8 = N-8;
    T9 = N-9;
    T10 = N-10;
    printf("%d",N);
    printf(" - 0 = ""%d\n",T0);
    printf("%d",N);
    printf(" - 1 = ""%d\n",T1);
    printf("%d",N);
    printf(" - 2 = ""%d\n",T2);
    printf("%d",N);
    printf(" - 3 = ""%d\n",T3);
    printf("%d",N);
    printf(" - 4 = ""%d\n",T4);
    printf("%d",N);
    printf(" - 5 = ""%d\n",T5);
    printf("%d",N);
    printf(" - 6 = ""%d\n",T6);
    printf("%d",N);
    printf(" - 7 = ""%d\n",T7);
    printf("%d",N);
    printf(" - 8 = ""%d\n",T8);
    printf("%d",N);
    printf(" - 9 = ""%d\n",T9);
    printf("%d",N);
    printf(" - 10 = ""%d\n",T10);
    printf("\n");
    printf("Tabuada de Multiplicação\n");
    printf("========================\n");
    T0 = N*0;
    T1 = N*1;
    T2 = N*2;
    T3 = N*3;
    T4 = N*4;
    T5 = N*5;
    T6 = N*6;
    T7 = N*7;
    T8 = N*8;
    T9 = N*9;
    T10 = N*10;
    printf("%d",N);
    printf(" * 0 = ""%d\n",T0);
    printf("%d",N);
    printf(" * 1 = ""%d\n",T1);
    printf("%d",N);
    printf(" * 2 = ""%d\n",T2);
    printf("%d",N);
    printf(" * 3 = ""%d\n",T3);
    printf("%d",N);
    printf(" * 4 = ""%d\n",T4);
    printf("%d",N);
    printf(" * 5 = ""%d\n",T5);
    printf("%d",N);
    printf(" * 6 = ""%d\n",T6);
    printf("%d",N);
    printf(" * 7 = ""%d\n",T7);
    printf("%d",N);
    printf(" * 8 = ""%d\n",T8);
    printf("%d",N);
    printf(" * 9 = ""%d\n",T9);
    printf("%d",N);
    printf(" * 10 = ""%d\n",T10);
    printf("\n");
    printf("Tabuada de Divisão\n");
    printf("==================\n");
    T1 = N/1;
    T2 = N/2;
    T3 = N/3;
    T4 = N/4;
    T5 = N/5;
    T6 = N/6;
    T7 = N/7;
    T8 = N/8;
    T9 = N/9;
    T10 = N/10;
    printf("%d",N);
    printf(" / 0 = Não divisível\n");
    printf("%d",N);
    printf(" / 1 = ""%d\n",T1);
    printf("%d",N);
    printf(" / 2 = ""%d\n",T2);
    printf("%d",N);
    printf(" / 3 = ""%d\n",T3);
    printf("%d",N);
    printf(" / 4 = ""%d\n",T4);
    printf("%d",N);
    printf(" / 5 = ""%d\n",T5);
    printf("%d",N);
    printf(" / 6 = ""%d\n",T6);
    printf("%d",N);
    printf(" / 7 = ""%d\n",T7);
    printf("%d",N);
    printf(" / 8 = ""%d\n",T8);
    printf("%d",N);
    printf(" / 9 = ""%d\n",T9);
    printf("%d",N);
    printf(" / 10 = ""%d\n",T10);

    return 0;
}
